/**
 * Trentino Stage API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ApiApplicationsListGet200ResponseInner {
    /**
    * The ID of the company that created the position.
    */
    'issuerId'?: string;
    /**
    * The title of the position.
    */
    'title'?: string;
    /**
    * A description of the position.
    */
    'description'?: string;
    /**
    * The sector of the position.
    */
    'sector'?: string;
    /**
    * The location of the position.
    */
    'location'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "issuerId",
            "baseName": "issuer_id",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "sector",
            "baseName": "sector",
            "type": "string"
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ApiApplicationsListGet200ResponseInner.attributeTypeMap;
    }
}

