/**
 * Trentino Stage API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ApiProfilesGetGet200Response {
    'name'?: string;
    'surname'?: string;
    'bio'?: string;
    'website'?: string;
    'birth_date'?: string;
    'address'?: {
        address?: string;
        city?: string;
        country?: string;
        region?: string;
        postalCode?: string;
    };
    'identifier'?: string;
    'sector'?: string;
    'cv'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "surname",
            "baseName": "surname",
            "type": "string"
        },
        {
            "name": "bio",
            "baseName": "bio",
            "type": "string"
        },
        {
            "name": "website",
            "baseName": "website",
            "type": "string"
        },
        {
            "name": "birthDate",
            "baseName": "birthDate",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string"
        },
        {
            "name": "sector",
            "baseName": "sector",
            "type": "string"
        },
        {
            "name": "cv",
            "baseName": "cv",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ApiProfilesGetGet200Response.attributeTypeMap;
    }
}

