/**
 * Trentino Stage API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ApiSessionVerifyGet200Response {
    /**
    * The profile ID associated with the session token
    */
    'profileId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "profileId",
            "baseName": "profileId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ApiSessionVerifyGet200Response.attributeTypeMap;
    }
}

